import type { Tenant } from "../types/tenant.types";

const MOCK = [
{"id":1,"companyName":"Willms, Schiller and Krajcik","tradingName":"Devify","documentNumber":"KL9667","subdomain":"gnu.org","isActive":false},
{"id":2,"companyName":"Braun and Sons","tradingName":"Mynte","documentNumber":"TG9561","subdomain":"cmu.edu","isActive":false},
{"id":3,"companyName":"Lehner, Grady and Balistreri","tradingName":"Zoovu","documentNumber":"EK3314","subdomain":"biglobe.ne.jp","isActive":true},
{"id":4,"companyName":"Feeney Inc","tradingName":"Browsedrive","documentNumber":"SQ9889","subdomain":"japanpost.jp","isActive":false},
{"id":5,"companyName":"Fisher, Hermann and Reichel","tradingName":"Oyope","documentNumber":"AC7067","subdomain":"house.gov","isActive":true},
{"id":6,"companyName":"Hodkiewicz Inc","tradingName":"Youspan","documentNumber":"LA9192","subdomain":"diigo.com","isActive":true},
{"id":7,"companyName":"Reilly, Feil and Rippin","tradingName":"Jamia","documentNumber":"NH9241","subdomain":"e-recht24.de","isActive":false},
{"id":8,"companyName":"Schulist Group","tradingName":"Npath","documentNumber":"AI2869","subdomain":"google.com.hk","isActive":false},
{"id":9,"companyName":"Rogahn-Koch","tradingName":"Topicblab","documentNumber":"DL1375","subdomain":"va.gov","isActive":false},
{"id":10,"companyName":"Abernathy Inc","tradingName":"Topiclounge","documentNumber":"NH5510","subdomain":"sbwire.com","isActive":true},
{"id":11,"companyName":"Nienow and Sons","tradingName":"Jayo","documentNumber":"QR6757","subdomain":"statcounter.com","isActive":false},
{"id":12,"companyName":"Beer-Larkin","tradingName":"Voonte","documentNumber":"NH1262","subdomain":"upenn.edu","isActive":true},
{"id":13,"companyName":"Prosacco, Schamberger and Beahan","tradingName":"Zoozzy","documentNumber":"DL7317","subdomain":"bizjournals.com","isActive":true},
{"id":14,"companyName":"Howell-Leuschke","tradingName":"Kare","documentNumber":"AI1448","subdomain":"google.com.br","isActive":true},
{"id":15,"companyName":"Batz, MacGyver and Hauck","tradingName":"Brainlounge","documentNumber":"KE8185","subdomain":"webeden.co.uk","isActive":false},
{"id":16,"companyName":"Baumbach-Gutmann","tradingName":"Wordtune","documentNumber":"NH8860","subdomain":"rambler.ru","isActive":true},
{"id":17,"companyName":"Nitzsche-Marks","tradingName":"Youspan","documentNumber":"NH7999","subdomain":"blogspot.com","isActive":false},
{"id":18,"companyName":"McGlynn and Sons","tradingName":"Babbleblab","documentNumber":"KL4848","subdomain":"ucoz.com","isActive":false},
{"id":19,"companyName":"Gerlach, Friesen and Kreiger","tradingName":"Layo","documentNumber":"CX9412","subdomain":"wikimedia.org","isActive":true},
{"id":20,"companyName":"Lesch and Sons","tradingName":"Browsecat","documentNumber":"AM7321","subdomain":"noaa.gov","isActive":true},
{"id":21,"companyName":"Flatley, Champlin and Schoen","tradingName":"Edgeify","documentNumber":"AZ3116","subdomain":"indiegogo.com","isActive":true},
{"id":22,"companyName":"Ruecker, Bruen and Altenwerth","tradingName":"Skaboo","documentNumber":"EK7699","subdomain":"miibeian.gov.cn","isActive":true},
{"id":23,"companyName":"Flatley-Gerhold","tradingName":"Oba","documentNumber":"AZ3766","subdomain":"linkedin.com","isActive":false},
{"id":24,"companyName":"Legros, Pfannerstill and Turner","tradingName":"Skinte","documentNumber":"ET7368","subdomain":"booking.com","isActive":true},
{"id":25,"companyName":"Kiehn-Heller","tradingName":"Quimba","documentNumber":"BA1149","subdomain":"multiply.com","isActive":false},
{"id":26,"companyName":"Heller-Mann","tradingName":"Kamba","documentNumber":"KE6531","subdomain":"hatena.ne.jp","isActive":true},
{"id":27,"companyName":"O'Reilly, Heidenreich and Reichert","tradingName":"Quimba","documentNumber":"WN1798","subdomain":"cam.ac.uk","isActive":false},
{"id":28,"companyName":"Towne, McGlynn and Erdman","tradingName":"Yata","documentNumber":"LA3827","subdomain":"stumbleupon.com","isActive":true},
{"id":29,"companyName":"Hamill Inc","tradingName":"Buzzdog","documentNumber":"SQ3016","subdomain":"comsenz.com","isActive":true},
{"id":30,"companyName":"O'Kon Group","tradingName":"Photobug","documentNumber":"KE9016","subdomain":"google.nl","isActive":false},
{"id":31,"companyName":"Bauch Group","tradingName":"Livetube","documentNumber":"AM2718","subdomain":"reddit.com","isActive":true},
{"id":32,"companyName":"Schamberger-Macejkovic","tradingName":"Riffpath","documentNumber":"AM9131","subdomain":"forbes.com","isActive":true},
{"id":33,"companyName":"Dicki, Lowe and McCullough","tradingName":"Quinu","documentNumber":"NZ7374","subdomain":"skyrock.com","isActive":false},
{"id":34,"companyName":"Feil, Barton and Kuhn","tradingName":"Yata","documentNumber":"SQ4120","subdomain":"rambler.ru","isActive":false},
{"id":35,"companyName":"Feest and Sons","tradingName":"Layo","documentNumber":"CX4972","subdomain":"sakura.ne.jp","isActive":true},
{"id":36,"companyName":"Schumm Inc","tradingName":"Trilith","documentNumber":"NZ3672","subdomain":"wiley.com","isActive":true},
{"id":37,"companyName":"Rowe-Bins","tradingName":"Feedfire","documentNumber":"SK2386","subdomain":"ow.ly","isActive":true},
{"id":38,"companyName":"Hahn-Schultz","tradingName":"Cogidoo","documentNumber":"SQ9336","subdomain":"cloudflare.com","isActive":false},
{"id":39,"companyName":"Torphy Group","tradingName":"Thoughtworks","documentNumber":"QF6243","subdomain":"geocities.jp","isActive":false},
{"id":40,"companyName":"Rosenbaum Group","tradingName":"Browseblab","documentNumber":"DL1765","subdomain":"fotki.com","isActive":false},
{"id":41,"companyName":"Bergnaum, Klein and Gulgowski","tradingName":"Minyx","documentNumber":"IB4379","subdomain":"sciencedaily.com","isActive":false},
{"id":42,"companyName":"Green-Kulas","tradingName":"Twitterbeat","documentNumber":"QR7416","subdomain":"hugedomains.com","isActive":true},
{"id":43,"companyName":"McGlynn-Hudson","tradingName":"Muxo","documentNumber":"LA7613","subdomain":"wordpress.org","isActive":false},
{"id":44,"companyName":"Rolfson-Runolfsson","tradingName":"Demivee","documentNumber":"WN7820","subdomain":"columbia.edu","isActive":false},
{"id":45,"companyName":"Corkery, Schmitt and Bayer","tradingName":"Vidoo","documentNumber":"SQ9484","subdomain":"ft.com","isActive":false},
{"id":46,"companyName":"Treutel Group","tradingName":"Twinder","documentNumber":"ET4833","subdomain":"plala.or.jp","isActive":true},
{"id":47,"companyName":"Kautzer Group","tradingName":"Kamba","documentNumber":"IB6789","subdomain":"php.net","isActive":false},
{"id":48,"companyName":"Wyman LLC","tradingName":"Jetpulse","documentNumber":"LA1166","subdomain":"marriott.com","isActive":false},
{"id":49,"companyName":"Bahringer Group","tradingName":"Skinte","documentNumber":"SA5199","subdomain":"symantec.com","isActive":true},
{"id":50,"companyName":"Sporer-Bernier","tradingName":"Quimm","documentNumber":"AZ8496","subdomain":"dedecms.com","isActive":false},
{"id":51,"companyName":"Hayes, Crooks and Volkman","tradingName":"Ntag","documentNumber":"IB2276","subdomain":"cam.ac.uk","isActive":true},
{"id":52,"companyName":"Mayert LLC","tradingName":"Ailane","documentNumber":"CX8815","subdomain":"netvibes.com","isActive":false},
{"id":53,"companyName":"Bailey Group","tradingName":"Livepath","documentNumber":"QF3040","subdomain":"redcross.org","isActive":true},
{"id":54,"companyName":"Konopelski, Schmidt and Mosciski","tradingName":"Twitterwire","documentNumber":"BA7889","subdomain":"stumbleupon.com","isActive":true},
{"id":55,"companyName":"Hartmann, Schinner and Kertzmann","tradingName":"Trilia","documentNumber":"QF5171","subdomain":"com.com","isActive":false},
{"id":56,"companyName":"Crooks, Rempel and Gutkowski","tradingName":"Thoughtbeat","documentNumber":"LA2548","subdomain":"answers.com","isActive":true},
{"id":57,"companyName":"Boyer Group","tradingName":"Quimm","documentNumber":"NH7905","subdomain":"omniture.com","isActive":true},
{"id":58,"companyName":"Goodwin, O'Connell and Schneider","tradingName":"Youopia","documentNumber":"LA4220","subdomain":"princeton.edu","isActive":false},
{"id":59,"companyName":"Murazik, Boyer and Cronin","tradingName":"Livetube","documentNumber":"LA9236","subdomain":"xrea.com","isActive":true},
{"id":60,"companyName":"Turner, Connelly and Cummerata","tradingName":"Edgeblab","documentNumber":"TG3624","subdomain":"symantec.com","isActive":true},
{"id":61,"companyName":"Rippin-Kilback","tradingName":"Yakijo","documentNumber":"AC8594","subdomain":"eepurl.com","isActive":true},
{"id":62,"companyName":"Kub-Hudson","tradingName":"Tagopia","documentNumber":"IB2817","subdomain":"blog.com","isActive":true},
{"id":63,"companyName":"Dach LLC","tradingName":"Aivee","documentNumber":"NZ9438","subdomain":"usda.gov","isActive":false},
{"id":64,"companyName":"Glover, Bruen and Pfannerstill","tradingName":"Agivu","documentNumber":"AV3374","subdomain":"indiegogo.com","isActive":false},
{"id":65,"companyName":"Mann LLC","tradingName":"Divavu","documentNumber":"AI3110","subdomain":"prweb.com","isActive":true},
{"id":66,"companyName":"Boehm and Sons","tradingName":"Quinu","documentNumber":"AF1538","subdomain":"sbwire.com","isActive":true},
{"id":67,"companyName":"Denesik-Runolfsson","tradingName":"Oyoba","documentNumber":"ET7440","subdomain":"goodreads.com","isActive":true},
{"id":68,"companyName":"Jacobs Inc","tradingName":"Brainlounge","documentNumber":"AF1050","subdomain":"wp.com","isActive":true},
{"id":69,"companyName":"Rolfson and Sons","tradingName":"Twiyo","documentNumber":"AV1895","subdomain":"yellowpages.com","isActive":true},
{"id":70,"companyName":"Toy, Senger and Goodwin","tradingName":"Aimbo","documentNumber":"UA8491","subdomain":"sohu.com","isActive":false},
{"id":71,"companyName":"Brown LLC","tradingName":"Centidel","documentNumber":"AF9449","subdomain":"google.co.uk","isActive":true},
{"id":72,"companyName":"Beahan, Rath and Berge","tradingName":"Photojam","documentNumber":"SK7047","subdomain":"oakley.com","isActive":true},
{"id":73,"companyName":"Davis LLC","tradingName":"Meeveo","documentNumber":"AF4682","subdomain":"vk.com","isActive":true},
{"id":74,"companyName":"Mitchell, Kreiger and Dare","tradingName":"Meevee","documentNumber":"AI8128","subdomain":"blog.com","isActive":true},
{"id":75,"companyName":"Nader, Morar and Dare","tradingName":"Devbug","documentNumber":"BA8026","subdomain":"deviantart.com","isActive":false},
{"id":76,"companyName":"Deckow-Schneider","tradingName":"Fivebridge","documentNumber":"SA2680","subdomain":"bloglovin.com","isActive":false},
{"id":77,"companyName":"Thompson-Hudson","tradingName":"Aivee","documentNumber":"SA8513","subdomain":"jugem.jp","isActive":false},
{"id":78,"companyName":"Fritsch Group","tradingName":"Camido","documentNumber":"AZ6460","subdomain":"xrea.com","isActive":true},
{"id":79,"companyName":"Mohr LLC","tradingName":"Oloo","documentNumber":"AC3869","subdomain":"csmonitor.com","isActive":false},
{"id":80,"companyName":"Hagenes-Lehner","tradingName":"Dabfeed","documentNumber":"NZ6357","subdomain":"ox.ac.uk","isActive":true},
{"id":81,"companyName":"Stiedemann-Kautzer","tradingName":"Edgetag","documentNumber":"AA4882","subdomain":"alexa.com","isActive":true},
{"id":82,"companyName":"Wolf, Casper and Green","tradingName":"Yabox","documentNumber":"NH1897","subdomain":"theatlantic.com","isActive":false},
{"id":83,"companyName":"Kling LLC","tradingName":"Edgepulse","documentNumber":"AC6343","subdomain":"cbc.ca","isActive":false},
{"id":84,"companyName":"Satterfield, Beier and Strosin","tradingName":"Twitternation","documentNumber":"EK5772","subdomain":"engadget.com","isActive":true},
{"id":85,"companyName":"Rutherford-Auer","tradingName":"Blogtags","documentNumber":"AI4546","subdomain":"acquirethisname.com","isActive":true},
{"id":86,"companyName":"Larson-Quigley","tradingName":"Zoomcast","documentNumber":"ET6504","subdomain":"i2i.jp","isActive":false},
{"id":87,"companyName":"Olson-Leuschke","tradingName":"Innotype","documentNumber":"UA5646","subdomain":"g.co","isActive":true},
{"id":88,"companyName":"Pfannerstill-Glover","tradingName":"Realbuzz","documentNumber":"BA9466","subdomain":"cpanel.net","isActive":true},
{"id":89,"companyName":"Rippin Inc","tradingName":"Browsecat","documentNumber":"ET4947","subdomain":"thetimes.co.uk","isActive":false},
{"id":90,"companyName":"Pagac-Hodkiewicz","tradingName":"Riffpedia","documentNumber":"NH7623","subdomain":"google.it","isActive":false},
{"id":91,"companyName":"Armstrong and Sons","tradingName":"Jabbersphere","documentNumber":"QF8880","subdomain":"ehow.com","isActive":true},
{"id":92,"companyName":"Franecki Inc","tradingName":"Topicstorm","documentNumber":"WN9336","subdomain":"ask.com","isActive":false},
{"id":93,"companyName":"Harris-Johns","tradingName":"Ntags","documentNumber":"AZ7115","subdomain":"npr.org","isActive":false},
{"id":94,"companyName":"Harber LLC","tradingName":"Yakitri","documentNumber":"QF5189","subdomain":"twitter.com","isActive":false},
{"id":95,"companyName":"Farrell-Greenfelder","tradingName":"Oba","documentNumber":"LH4742","subdomain":"opera.com","isActive":true},
{"id":96,"companyName":"Smitham, Will and Jenkins","tradingName":"Voolith","documentNumber":"KL2846","subdomain":"liveinternet.ru","isActive":false},
{"id":97,"companyName":"Kunze-Lemke","tradingName":"Brightbean","documentNumber":"AZ4341","subdomain":"gnu.org","isActive":false},
{"id":98,"companyName":"Ledner-Ledner","tradingName":"Browsebug","documentNumber":"SA4236","subdomain":"de.vu","isActive":true},
{"id":99,"companyName":"Funk Inc","tradingName":"Innotype","documentNumber":"IB3698","subdomain":"merriam-webster.com","isActive":false},
{"id":100,"companyName":"Johnston-Blick","tradingName":"Npath","documentNumber":"QF2974","subdomain":"bloglines.com","isActive":true}];

export const MOCK_DATA: Tenant[] = MOCK.map(item => ({
  ...item,
  id: String(item.id), // Converte o id numérico do MOCK para string
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString()
}));